// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#YQQOPOOOOOO'#C^'#C^OYOQO'#C_ObOPO'#CeQOOOOOOOOO'#Cc'#CcOYOQO,58yOOOO'#Ca'#CaOmOQO,58yOOOO,59P,59POOOO-E6a-E6aOuOQO1G.eOuOQO1G.eOOOO1G.e1G.eO}OQO7+$POOOO7+$P7+$POOOO<<Gk<<Gk",
  stateData: "!V~OSQOYPO~OZTO[VO~OSQOYPOWXX~OU]OZTO~OU_OZTO~OU`OZTO~O",
  goto: "yYPPZZP_PePsTRORQWQRZUQUQUYU[^Q[WR^ZQSORXR",
  nodeNames: "⚠ Program Text Expression { Argument }",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&t~RrOX#]X^#w^p#]pq#wq!Q#]!Q![%m![!c#]!c!}%m!}#R#]#R#S%m#S#T#]#T#o%m#o#p&j#p#q#]#q#r&o#r#y#]#y#z#w#z$f#]$f$g#w$g#BY#]#BY#BZ#w#BZ$IS#]$IS$I_#w$I_$I|#]$I|$JO#w$JO$JT#]$JT$JU#w$JU$KV#]$KV$KW#w$KW&FU#]&FU&FV#w&FV;'S#];'S;=`#q<%lO#]P#bTYPO#o#]#p#q#]#r;'S#];'S;=`#q<%lO#]P#tP;=`<%l#]R$OiYPZQOX#]X^#w^p#]pq#wq#o#]#p#q#]#r#y#]#y#z#w#z$f#]$f$g#w$g#BY#]#BY#BZ#w#BZ$IS#]$IS$I_#w$I_$I|#]$I|$JO#w$JO$JT#]$JT$JU#w$JU$KV#]$KV$KW#w$KW&FU#]&FU&FV#w&FV;'S#];'S;=`#q<%lO#]R%t[[QYPO!Q#]!Q![%m![!c#]!c!}%m!}#R#]#R#S%m#S#T#]#T#o%m#p#q#]#r;'S#];'S;=`#q<%lO#]~&oOS~~&tOU~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
