// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#YQQOPOOOOOO'#C^'#C^OYOQO'#CfObOPO'#CdQOOOOOOOOO'#Cb'#CbOYOQO,59QOOOO'#C`'#C`OmOQO,59QOOOO,59O,59OOOOO-E6`-E6`OuOQO1G.lOuOQO1G.lOOOO1G.l1G.lO}OQO7+$WOOOO7+$W7+$WOOOO<<Gr<<Gr",
  stateData: "!V~ORQOXPO~OZTO[VO~ORQOXPOVWX~OT]OZTO~OT_OZTO~OT`OZTO~O",
  goto: "zZPP[P`PfPtP[TRORQWQRZUQUQUYU[^Q[WR^ZQSORXR",
  nodeNames: "⚠ Program Text { Param }",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "(w~RtOX#cX^%`^p#cpq%`qw#cwx#zx!Q#c!Q!['X![!c#c!c!}'X!}#R#c#R#S'X#S#T#c#T#o'X#o#p(X#p#q#c#q#r(^#r#y#c#y#z%`#z$f#c$f$g%`$g#BY#c#BY#BZ%`#BZ$IS#c$IS$I_%`$I_$I|#c$I|$JO%`$JO$JT#c$JT$JU%`$JU$KV#c$KV$KW%`$KW&FU#c&FU&FV%`&FV;'S#c;'S;=`%Y<%lO#cP#hUXPOw#cwx#zx#o#c#p;'S#c;'S;=`%Y<%lO#cP#}XOw#cwx$jx#o#c#o#p$j#p;'S#c;'S;=`%Y<%l~#c~O#c~~#cP$mVOw$jwx#cx;'S$j;'S;=`%S<%l~$j~O$j~~#cP%VP;=`<%l$jP%]P;=`<%l#cR%gjXPZQOX#cX^%`^p#cpq%`qw#cwx#zx#o#c#p#y#c#y#z%`#z$f#c$f$g%`$g#BY#c#BY#BZ%`#BZ$IS#c$IS$I_%`$I_$I|#c$I|$JO%`$JO$JT#c$JT$JU%`$JU$KV#c$KV$KW%`$KW&FU#c&FU&FV%`&FV;'S#c;'S;=`%Y<%lO#cR'`][QXPOw#cwx#zx!Q#c!Q!['X![!c#c!c!}'X!}#R#c#R#S'X#S#T#c#T#o'X#p;'S#c;'S;=`%Y<%lO#c~(^OR~R(eUTQXPOw#cwx#zx#o#c#p;'S#c;'S;=`%Y<%lO#c",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
