// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  TextRoot = 2,
  ExpressionOpen = 3,
  FormatExpression = 5,
  Param = 6,
  FormatFunction = 7,
  FormatStyle = 8,
  PluralExpression = 9,
  PluralVariant = 11,
  VariantDescriptor = 12,
  Text = 13,
  PluralPlaceholder = 14,
  ExpressionClose = 16
