// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#YQQOPOOOOOO'#C^'#C^OYOQO'#CfObOPO'#CdQOOOOOOOOO'#Cb'#CbOYOQO,59QOOOO'#C`'#C`OmOQO,59QOOOO,59O,59OOOOO-E6`-E6`OuOQO1G.lOuOQO1G.lOOOO1G.l1G.lO}OQO7+$WOOOO7+$W7+$WOOOO<<Gr<<Gr",
  stateData: "!V~ORQOXPO~OZTO[VO~ORQOXPOVWX~OT]OZTO~OT_OZTO~OT`OZTO~O",
  goto: "zZPP[P`PfPtP[TRORQWQRZUQUQUYU[^Q[WR^ZQSORXR",
  nodeNames: "⚠ Program Text { Param }",
  maxTerm: 12,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "(r~RtOX#cX^%i^p#cpq%iqw#cwx#}x!Q#c!Q!['e![!c#c!c!}'e!}#R#c#R#S'e#S#T#c#T#o'e#o#p(h#p#q#c#q#r(m#r#y#c#y#z%i#z$f#c$f$g%i$g#BY#c#BY#BZ%i#BZ$IS#c$IS$I_%i$I_$I|#c$I|$JO%i$JO$JT#c$JT$JU%i$JU$KV#c$KV$KW%i$KW&FU#c&FU&FV%i&FV;'S#c;'S;=`%c<%lO#cP#hVXPOw#cwx#}x#o#c#p#q#c#r;'S#c;'S;=`%c<%lO#cP$QZOw#cwx$sx#o#c#o#p$s#p#q#c#q#r$s#r;'S#c;'S;=`%c<%l~#c~O#c~~#cP$vVOw$swx#cx;'S$s;'S;=`%]<%l~$s~O$s~~#cP%`P;=`<%l$sP%fP;=`<%l#cR%pkXPZQOX#cX^%i^p#cpq%iqw#cwx#}x#o#c#p#q#c#r#y#c#y#z%i#z$f#c$f$g%i$g#BY#c#BY#BZ%i#BZ$IS#c$IS$I_%i$I_$I|#c$I|$JO%i$JO$JT#c$JT$JU%i$JU$KV#c$KV$KW%i$KW&FU#c&FU&FV%i&FV;'S#c;'S;=`%c<%lO#cR'l^[QXPOw#cwx#}x!Q#c!Q!['e![!c#c!c!}'e!}#R#c#R#S'e#S#T#c#T#o'e#p#q#c#r;'S#c;'S;=`%c<%lO#c~(mOR~~(rOT~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
