export { getPlaceholders } from "./parser/placeholders/getPlaceholders";
export { PlaceholderPlugin } from "./parser/PlaceholderPlugin";
export { parser as tolgeeParser } from "./parser/lezer/tolgeeParser";
export { tolgeeSyntax } from "./parser/tolgeeSyntax";
export { TolgeeHighlight } from "./parser/tolgeeHighlight";
export { htmlIsolatesPlugin } from "./parser/htmlIsolatesPlugin";
export { generatePlaceholdersStyle } from "./parser/placeholdersStyle";
export { tolgeeFormatGenerateIcu } from "./parser/tolgeeFormatGenerateIcu";
export { checkParamNameIsValid } from "./parser/checkParamNameIsValid";
export { getTolgeePlurals } from "./parser/getTolgeePlurals";
export { getTolgeeFormat } from "./parser/getTolgeeFormat";
export { getFirstPluralParameter } from "./parser/getFirstPluralParameter";
export { getPluralVariants, getVariantExample } from "./utils/pluralTools";
export { getLanguageDirection } from "./utils/getLanguageDirection";
export { getPluralRules, selectPluralRule } from "./utils/plurals";
export * from "./parser/types";
