name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test


  static-check:
    name: Static check 🪲
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm

      - name: Install
        run: npm ci
        
      - name: Eslint
        run: npm run eslint

      - name: Typescript
        run: npm run tsc

